spring.application.name=authservice
spring.profiles.default=local
jwt.secret=bWlfY2xhdmVfc2VjcmV0YQ0K
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.main.authservice=INFO
logging.level.org.springframework.security=WARN
