spring.application.name=authservice
spring.profiles.default=local
jwt.secret=bWlfY2xhdmVfc2VjcmV0YQ0K
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
server.forward-headers-strategy=framework
app.cors.allowed-origins=http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173
logging.level.com.main.authservice=INFO
logging.level.org.springframework.security=WARN
logging.pattern.level=%5p [cid:%X{correlationId:-none}]
