spring.datasource.url=jdbc:h2:mem:authservice;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=uk0gORcK9s44BEM5QcB8x5lNLWgaTVsBfc2A1FchfYI=
app.bootstrap.admin-token=6Z5AYKwd2Q+0YcdHpjr+vtF2gzsEcXDgzziQYq1LiqI=
